module.exports = {
  'plugins': [
    'github'
  ],
  'rules': {
    'array-bracket-spacing': 'error',
    'arrow-parens': ['error', 'as-needed'],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
    'camelcase': ['error', {'properties': 'always'}],
    'comma-dangle': ['error', 'never'],
    'eol-last': 'error',
    'eqeqeq': ['error', 'smart'],
    'func-style': ['error', 'declaration'],
    'github/no-implicit-buggy-globals': 'error',
    'github/no-sprockets-directives': 'error',
    'github/no-unused-disabled-rules': 'error',
    'indent': ['error', 2, {'SwitchCase': 1}],
    'keyword-spacing': 'error',
    'new-parens': 'error',
    'no-extra-parens': 'error',
    'no-implicit-globals': 'error',
    'no-invalid-this': 'error',
    'no-multi-spaces': 'error',
    'no-return-assign': 'error',
    'no-spaced-func': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-unexpected-multiline': 'error',
    'object-curly-spacing': 'error',
    'prefer-promise-reject-errors': 'error',
    'quotes': ['error', 'single'],
    'semi': ['error', 'never'],
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': ['error', 'never'],
    'wrap-iife': ['error', 'inside']
  },
  'extends': 'eslint:recommended'
}
