module.exports = {
  'plugins': [
    'github'
  ],
  'rules': {
    'array-bracket-spacing': 'error',
    'arrow-parens': ['error', 'as-needed'],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
    'camelcase': ['error', {'properties': 'always'}],
    'comma-dangle': ['error', 'never'],
    'constructor-super': 'error',
    'eol-last': 'error',
    'eqeqeq': ['error', 'smart'],
    'func-style': ['error', 'declaration'],
    'github/no-implicit-buggy-globals': 'error',
    'github/no-sprockets-directives': 'error',
    'github/no-unused-disabled-rules': 'error',
    'indent': ['error', 2, {'SwitchCase': 1}],
    'keyword-spacing': 'error',
    'new-parens': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-console': 'error',
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': ['error', 'all', {'conditionalAssign': false, 'returnAssign': false, 'nestedBinaryExpressions': false, 'enforceForArrowConditionals': false}],
    'no-extra-semi': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implicit-globals': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'error',
    'no-irregular-whitespace': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-spaces': 'error',
    'no-new-symbol': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-return-assign': 'error',
    'no-self-assign': 'error',
    'no-spaced-func': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-labels': 'error',
    'no-unused-vars': 'error',
    'no-useless-escape': 'error',
    'object-curly-spacing': 'error',
    'object-shorthand': ['error', 'always', {'avoidQuotes': true}],
    'prefer-promise-reject-errors': 'error',
    'quotes': ['error', 'single'],
    'require-yield': 'error',
    'semi': ['error', 'never'],
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': ['error', 'never'],
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'wrap-iife': ['error', 'inside']
  }
}
